### ISSUE TITLE
anki crashes after closing the nidd pop-up window

### ISSUE THREAD

**Issue by chunhan1928** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#14]
I click the nidd in my card, and it opens a pop-up window. I close the nidd pop-up window, and Anki crashes.
hardware and software: MacOS 12.5.1, anki Version ⁨2.1.54.

**Comment by ijgnd** [comment]
Thanks for reporting this important issue.

I will look into this on the weekend when I have some time.

**Comment by ijgnd** [comment]
note to self:

- this only happens on MacOS with Anki version 2.1.50 or later.
- similar bug that crashed only Anki 2.1.50+ on MacOS when using the editor with my add-on [extended html editor for fields and card templates (with some versioning)](https://ankiweb.net/shared/info/1043915942) , see https://github.com/ijgnd/anki__editor_edit_html_extended/issues/6#issuecomment-1242434977 . The

**Comment by ijgnd** [comment]
Could you test the following version? 

I attached an .ankiaddon file that you can drag and drop into the add-on window of Anki to install it.

The problem is that github does not allow me to upload files with the extension "ankiaddon". So I renamed it to ".ankiaddon.zip". After downloading it remove ".zip" from the file name, i.e. rename it to just `anki__preview_card_edit_note_in_extra_window_linked_from_reviewer__2022-10-07.ankiaddon`.

Despite their different extension ".ankiaddon" files are just zip files. So you can check for yourself what this file contains before installing it.

Let me know if it works and/or if I there are different bugs ...

[anki__preview_card_edit_note_in_extra_window_linked_from_reviewer__2022-10-07.ankiaddon.zip](https://github.com/ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer/files/9737502/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer__2022-10-07.ankiaddon.zip)

**Comment by chunhan1928** [comment]
It seems to be working!!! Didn't see a bug yet, but i didn't read the code, so i can't be 100% sure. (i am not good enough to understand how add-ons work ><)

**Comment by ijgnd** [comment]
Thanks. I've just uploaded this to ankiweb.

In case your wondering how this obvious bug could occur: I don't have a Mac and I'm still not on Anki 2.1.50+ (because the Custom Styles add-on hasn't been updated yet).
